GET http://localhost:5289/

GET http://localhost:5289/api/test/search?q=anxiety

GET http://localhost:5289/debug/routes

POST http://localhost:5289/api/test/advise
Content-Type: application/json

{
    "text": "I am anxious about my future"
}